### ISSUE TITLE
Bounty for fixing bugs and improving mobile experience

### ISSUE THREAD

**Issue by strixaluco** [frappe/cordova-wrapper#14]
Link to the bounty: https://www.bountysource.com/issues/48390608-bounty-for-fixing-bugs-and-improving-mobile-experience

The main goal of this small campaign is to fix several nastiest bugs and to implement automatic credentials saving.

- [x] #8 [Error] Failed to load webpage with error;
- [x] #13 [Bug] "The image couldn't be loaded" error in Image view;
- [ ] #11 [Feature] Remember username / password.

In case campaign gets enough traction and receives more funds, we might include other features as well (probably for the second phase):

- [ ] #7 [Feature] OAuth Login;
- [ ] #12 [Feature] Push notifications 
- [ ] frappe/erpnext/issues/7306 [Feature] Attachment support

**Comment by OneiricIT** [comment]
@strixaluco also add in ability to open attachments - see https://github.com/frappe/erpnext/issues/7306 

Also ability for app to change to landscape as all my testing shows it stays portrait on phone.

**Comment by strixaluco** [comment]
@OneiricIT , thank you for suggestions! I've added attachments support to the list.
Regarding the landscape mode, @cgpurbaugh already submitted PR last year, but for some reason it is not merged still — frappe/mobile/pull/4

**Comment by strixaluco** [comment]
@OneiricIT PR for landscape mode on iOS has just been [merged](https://github.com/frappe/mobile/commit/bea7b978ecb2dcf0ee57c5bd23861509c5eaba57) by Rushabh Mehta. 
Now just to wait for new version to be built and published.

**Comment by rmehta** [comment]
@strixaluco please feel free to ping any maintainer if there are pulls pending to be merged. I personally have all github notifications switched off. So don't get any by default.

**Comment by strixaluco** [comment]
@rmehta thanks for pointing this out, will do from now on.

**Comment by marciogurka** [comment]
@strixaluco is this still needed??? I saw [here](https://www.bountysource.com/issues/48390608-bounty-for-fixing-bugs-and-improving-mobile-experience) what you want and I think I could work on it...

**Comment by strixaluco** [comment]
Hi. Thanks for getting onto this! 
May we continue the talk at the [forum thread](https://discuss.erpnext.com/t/bounty-fixing-bugs-and-improving-mobile-experience-of-erpnext-now-250)?

**Comment by bghayad** [comment]
Hello @strixaluco 
I am interested in all these features and the most is the push notification.
Also I am interested in resolving new additional issues that will mention it, but how much it is remaining to pay and then we can move on and finish all the mentioned issues including those that I will add them? 
Below are the issues that need to be included in this bounty, please I need to know the needed money and time:
- In the list view of the mobile, we need to see more than one column? How I can determine the columns to be displayed? For example, in the Tasks, I need to say the Subject and the Priority, how to be able to achieve this? Or the Subject and the Priority and the Time?

- While entering the fields: if pressed on back, not to leave the document and go back to the list. But it should consider the back like escape. Is it possible?

- While adding item, the ability to add the item image from the mobile application (I mean the item image profile and not the attachment, as it is allowed to add the attachment but I am not able to add the item image). The same thing for all the doctype that has Image.

- If the mobile rotated and became in the width, then we should see more fields in the list view. 
- If mobile rotated and became in width, then it should do auto fitting (auto sizing) for the documents and showing two fields two fields instead of 1 field 1 field.

How much time and money this need to be finished?
Regards
Bilal

**Comment by strixaluco** [comment]
Hi, @bghayad. I'm glad you're interested in this initiative. We can easily include the list of your issues as well, but do you have people willing to work on it? I didn't have lots of success finding developers so far: https://discuss.erpnext.com/t/bounty-fixing-bugs-and-improving-mobile-experience-of-erpnext-now-250/27282

**Comment by bghayad** [comment]
Hi @strixaluco, no I do not have developer.
So what is the solution? How can we move on?

Regards
Bilal

**Comment by bghayad** [comment]
Hello @strixaluco 
If I placed additional 150$ as bounty, it will move forward? What do you think?
But needs to include my points.
Regards
Bilal

**Comment by strixaluco** [comment]
> If I placed additional 150$ as bounty, it will move forward?

That's not an easy question to answer. Your best bet might be to start a separate bounty related to your particular needs, as this one is kind of stalled and I'm not sure if diluting it with more requests is going to help. At the same time it can be helpful to chip in for the purpose of implementing push notifications, in case you want that.
We should probably try to promote the bounty more actively (e.g. on Upwork)
